force_keyboard_focus = true
selection_wrap = true
theme = "oxide-themes"
additional_theme_location = "~/.local/share/oxide/default/walker/"

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" } 

[keybinds]
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "menus",
  "websearch",
] # providers to be queried by default

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"
